
version: 2

sources:
  - name: commcare
    schema: test_airbyte_commcare
    database: postgres
    tables:
      - name: raw_form
        identifier: _airbyte_raw_form
        description: One record per form data. Includes duplicates and modified data.
        
  - name: survey-cto
    schema: public
    database: postgres
    tables:
      - name: raw_surveycto
        identifier: _airbyte_raw_surveycto_stream
        description: One record per form data. Includes duplicates and modified data.
       
models:
  - name: survey_form
    description: "Add survey form data" 
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
           
  - name: incremental
    description: "Incremental for the suvrvey cto data"
           
  - name: extract_form_params
    description: "Add form ids, and form names along with form data id - maybe this should be part of airbyte ingestion connector"
    columns:
      - name: _airbyte_ab_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: flatten_survey_data
    description: "Add coulmn"
    columns:
      - name: _airbyte_data

  - name: delete_duplicates
    description: "Deduped model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: unnest_json
    description: "Data json is unnested to single level - maybe this should be done in python"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: flat_json_columnar
    description: "Flat data with a couple of extracted component in columns - maybe python and will need schema"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
